### ISSUE TITLE
Crossbeam's try_xxx blocks, is that a problem?

### ISSUE THREAD

**Issue by Ten0** [qingstor/crossfire-rs#2]
[`channel-async`](https://lib.rs/crates/channel-async) was a futures channel based on `crossbeam-channel`, which was then deprecated [due to](https://github.com/dbcfd/channel-async/issues/6#issuecomment-598235374) crossbeam blocking even [in try_xxx](https://docs.rs/crossbeam-channel/0.4.3/src/crossbeam_channel/flavors/array.rs.html#310) ([`Backoff::snooze` doc](https://docs.rs/crossbeam/0.7.3/crossbeam/utils/struct.Backoff.html#method.snooze)).

Is this not an issue for this crate?

(Btw I guess this would be minor in any case since it locks for a shomewhat short amount of time, thanks a lot for the crate!)

**Comment by frostyplanet** [comment]
The basic idea of channel-async is a loop of try_recv()/try_send() and back-off with hard coded time with tokio::time, it does not block but it's inefficient,  try_recv()/ try_send does not block, but there's a cost when trying without sucess. So the author deprecate that crate.

This crate is also a wrap, but wakup machanism is base of std::task::Waker and crossbeam::queue, which are non-block. when sender blocks due to channel full, it will only waked up after a receiver consume message.

**Comment by frostyplanet** [comment]
There's a spin lock in every notification message (https://github.com/qingstor/crossfire-rs/blob/master/src/channel/locked_waker.rs#L93) , but the case is rare, the lock is short live and only fires when sender/receiver register an event before try_xxx and concurrently the other end got the same wake up event and do try_xxx
